scrape_configs:
  - job_name: 'pve' # PVE Exporter
    static_configs:
      - targets:
        - 192.168.2.100  # Proxmox VE node.
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.0.0.202:9221  # PVE exporter.
  - job_name: 'uptime' # Uptime-Kuma
    scrape_interval: 30s
    scheme: http
    static_configs:
      - targets: ['10.0.0.202:3001']
    basic_auth: 
      password: <UPTIMEKUMA_API_KEY>
  - job_name: 'caddy'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.0.0.233:2019']
